jobs:
- job: build
  displayName: Build
  strategy:
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: Release
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: foobar2000/foo_sample/foo_sample.sln
      platform: Win32
      configuration: $(configuration)
      msbuildArgs: /m
